### PR TITLE
Rescue trapped COMP in old Compound strategy

### PR DESCRIPTION
**Pull request by DanielVF**
We have comp left uncollected from our old Compound strategy. 

Collecting this will need to be done in two parts:

1. From the old governor, we will need to setRewardTokenAddress(COMP) on 0xD5433168Ed0B1F7714819646606DB509D9d8EC1f
2. We'l need to run this governance proposal, which will collect the comp, using the new governor.

### CODE REVIEW

**Review by franckc — APPROVED** [review]
Mig 26 LGTM

Regarding the gov proposal to execute on the old governor, the simplest might be to update the propose.js script and use that.

**Comment by DanielVF** [comment]
I've added a second deploy that creates a proposal from the old governor, to reactivate collecting COMP on the old strategy.

These two must be executed in order:

- First Prop 26 on the old governor
- Then Prop 27 on the current governor

As of 11/3/2021, running this two commands results in a 20K increase in the vaults holdings.

These should be good to go.

**Comment by DanielVF** [comment]
I'd love to go ahead and get these live. I'll go ahead and give submitting them a shot today.

**Comment by DanielVF** [comment]
Note that these proposals are on **DIFFERENT** governors.

Check method names and addresses

```
Running 026_comp_rescue_a deployment...
INFO: Sending proposal to governor...
INFO: Using governor contract at 0x830622BDd79CC677eE6594E20bBda5B26568b781
INFO: Submitting proposal for Re-enable rewards collection on old Compound strategy to governor 0x830622BDd79CC677eE6594E20bBda5B26568b781
INFO: Args: [
  [
    "0xD5433168Ed0B1F7714819646606DB509D9d8EC1f"
  ],
  [
    "setRewardTokenAddress(address)"
  ],
  [
    "0x000000000000000000000000c00e94cb662c3520282e6f5717214004a7f26888"
  ]
]
Gas price (gwei): Regular=119.742609525 Premium=136.506574858
INFO: Submitted proposal 6
INFO: Next step: call the following methods on the governor at 0x830622BDd79CC677eE6594E20bBda5B26568b781 via multi-sig
INFO:    queue(6)
INFO:    execute(6)
INFO: Done
INFO: Proposal sent.
026_comp_rescue_a deploy done.
...
Running 027_comp_rescue_b deployment...
INFO: Sending proposal to governor...
INFO: Submitting proposal for Collects COMP from old Contract to governor 0x72426BA137DEC62657306b12B1E869d43FeC6eC7
INFO: Args: [
  [
    "0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70",
    "0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70",
    "0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70"
  ],
  [
    "approveStrategy(address)",
    "harvestAndSwap(address)",
    "removeStrategy(address)"
  ],
  [
    "0x000000000000000000000000d5433168ed0b1f7714819646606db509d9d8ec1f",
    "0x000000000000000000000000d5433168ed0b1f7714819646606db509d9d8ec1f",
    "0x000000000000000000000000d5433168ed0b1f7714819646606db509d9d8ec1f"
  ]
]
Gas price (gwei): Regular=152.551334788 Premium=173.908521658
INFO: Submitted proposal 8
INFO: Next step: call the following methods on the governor at 0x72426BA137DEC62657306b12B1E869d43FeC6eC7 via multi-sig
INFO:    queue(8)
INFO:    execute(8)
INFO: Done
INFO: Proposal sent.
027_comp_rescue_b deploy done.
```

### Old Governor

image

### New Governor

image

**Pull request merged**
