### PR TITLE
Split out slither config

### PR DESCRIPTION
**Pull request by shahthepro**
- Exclude echidna and a few more unused contracts as well
- Adds a slither config file (instead of passing long args)

### CODE REVIEW

**Review by naddison36 — DISMISSED** [review]
Excellent idea

**Comment by naddison36** [comment]
@shahthepro the Slither action failed in the build for this. Can you fix before merging to master. Thanks

**Comment by shahthepro** [comment]
I haven't run it on triage mode, that should make the tests green. Will do it

**Review by sparrowDom — COMMENTED** [review]
nice cleanup!

**Pull request merged**
