### PR TITLE
add empty WOETH proxy

### PR DESCRIPTION
**Pull request by sparrowDom**
add empty WOETH proxy

WOETHProxy Address: `0xDcEe70654261AF21C44c093C300eD3Bb97b78192`
WOETH IMPL Address: `0xA539C0aA49c3D3a446ab0FFCd12413A7E0C5fE78`

### CODE REVIEW

**Review by franckc — APPROVED** [review]
Nice! LGTM

**Comment by DanielVF** [comment]
Confirmed deployed code matches code in repo. Confirmed deploy transactions

**Review by DanielVF — APPROVED** [review]

**Comment by DanielVF** [comment]
@sparrowDom Do you know why the unit tests are failing here? Would be good to have them passing before merge.

**Comment by sparrowDom** [comment]
Re-ran it and they passed

**Pull request merged**
