### PR TITLE
Add vault value checker

### PR DESCRIPTION
**Pull request by DanielVF**
https://etherscan.io/address/0x5B98B3255522E95f842967723Ee4Cc7dCEaa9150#code

When transferring funds into or out of curve pools, we need to check for possibly malicious price changes.

This contract is intended to be a part of a multisend, and should revert if prices turned unfavorable.

1. takeSnapshot()
2. ... do transfers
3. checkLoss(4000 * 1e18)

--- 

If you made a contract change, make sure to complete the checklist below before merging it in master.

Refer to our [documentation](https://github.com/OriginProtocol/security) for more details about contract security best practices.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. See [template](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review.md) and [example](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md).
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Review by mikeshultz — APPROVED** [review]
LGTM in and of itself.  Might have more questions if it were integrated into something.

**Comment by DanielVF** [comment]
> LGTM in and of itself. Might have more questions if it were integrated into something.

Yeah, hopefully will have the integration later today.

**Comment by DanielVF** [comment]
Found a tiny bug in the contract. Points to the spotter.

**Comment by mikeshultz** [comment]
> Found a tiny bug in the contract. Points to the spotter.

`checkLoss()` should be a `view`?  Only other thing I thought might be hinky was the use of `payable()` for the vault address but didn't think it had any real world impact.

**Comment by DanielVF** [comment]
Solidity 8 requires the vault to be payable, since it has a payable fallback. I'm not sure it makes sense to me.

**Comment by mikeshultz** [comment]
> Solidity 8 requires the vault to be payable, since it has a payable fallback. 

That's interesting.  I thought `payable` signified what you would use the address for, not the account's capabilities.  I seem to recall the technique of not using `payable` as a permissions/security feature to prevent sending of ETH to accounts.  Weird.

**Pull request merged**
