### PR TITLE
Localized Docs Link

### PR DESCRIPTION
**Pull request by ZaHuPro**
Related Issue: #239

### CODE REVIEW

**Review by franckc — APPROVED** [review]
Nice work! LGTM

**Comment by franckc** [comment]
@micahalcorn @sparrowDom Ok if we merge this PR in?

**Comment by micahalcorn** [comment]
@franckc sure, it looks good at a glance. I would recommend pushing a branch in the future rather than forking so that it's easier for us to pull and run locally. 🙂

**Comment by ZaHuPro** [comment]
@micahalcorn 
Thanks, I don't have the access to push. I think someone has to add me as a contributor.

**Comment by micahalcorn** [comment]
@ZaHuPro I think I added you, so just let me know if you don't find the email. 📬

**Comment by sparrowDom** [comment]
Nice job @ZaHuPro, looks good to me. And congrats on the first PR 👍

**Comment by ZaHuPro** [comment]
@micahalcorn Thanks, I got the mail upcoming fix I will push into a branch to a folk branch

**Comment by ZaHuPro** [comment]
@sparrowDom  Thanks

**Pull request merged**
