### PR TITLE
Deploy 086 - FrxEth Redeem Strategy

### PR DESCRIPTION
**Pull request by DanielVF**
## What

New strategy for OETH to be able to turn FrxEth into WETH via the official FrxEth redeem queue.

## Deployed contracts

|Name|Address|
|-|-|
|FrxEthRedeemStrategyProxy|0x95A8e45afCfBfEDd4A1d41836ED1897f3Ef40A9e|
|FrxEthRedeemStrategy|0xEFa87a78157Ccad82E4AE5925fbcB8a1E7fBC5Da|

## Governance action

Currently pending on gas prices, as  transaction https://etherscan.io/tx/0x9e546a8efbb678e042a723fc6e14995cb8d6f9027735907b0f48d19f3c12208e

Proposal ID: [22557697356425922748429758763228961417125309248972402797899806770489027739571](https://governance.ousd.com/#/22557697356425922748429758763228961417125309248972402797899806770489027739571)

### CODE REVIEW

**Comment by DanielVF** [comment]
My own deploy review check:

- [ ] All deployed contracts are listed in the deploy PR's description
- [ ] Deployed contract's verified code (and all dependencies) match the code in master
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal

**Comment by naddison36** [comment]
My verification

- [x] The governance proposal to add the FrxEth Redeem Strategy to the OETH Vault.
- [x] The deployed contract code matches the git branch `DanielVF/deploy_086`

```
sol2uml diff 0x95A8e45afCfBfEDd4A1d41836ED1897f3Ef40A9e .,node_modules -v

Compared the "FrxEthRedeemStrategyProxy" contract with address 0x95A8e45afCfBfEDd4A1d41836ED1897f3Ef40A9e on mainnet
to local files under folders ".,node_modules"

match   @openzeppelin/contracts/utils/Address.sol
match   contracts/governance/Governable.sol
match   contracts/proxies/InitializeGovernedUpgradeabilityProxy.sol
match   contracts/proxies/Proxies.sol
```

```
sol2uml diff 0xEFa87a78157Ccad82E4AE5925fbcB8a1E7fBC5Da .,node_modules -v

Compared the "FrxEthRedeemStrategy" contract with address 0xEFa87a78157Ccad82E4AE5925fbcB8a1E7fBC5Da on mainnet
to local files under folders ".,node_modules"

match   @openzeppelin/contracts/token/ERC20/IERC20.sol
match   @openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol
match   @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol
match   @openzeppelin/contracts/utils/Address.sol
match   @openzeppelin/contracts/utils/math/SafeMath.sol
match   contracts/governance/Governable.sol
match   contracts/interfaces/IBasicToken.sol
match   contracts/interfaces/IStrategy.sol
match   contracts/interfaces/IVault.sol
match   contracts/interfaces/IWETH9.sol
match   contracts/strategies/FrxEthRedeemStrategy.sol
match   contracts/token/OUSD.sol
match   contracts/utils/Helpers.sol
match   contracts/utils/Initializable.sol
match   contracts/utils/InitializableAbstractStrategy.sol
match   contracts/utils/InitializableERC20Detailed.sol
match   contracts/utils/StableMath.sol
match   contracts/vault/VaultStorage.sol
```

**Review by naddison36 — DISMISSED** [review]
LGTM

**Review by shahthepro — DISMISSED** [review]
- [x] All deployed contracts are listed in the deploy PR's description
- [x] Deployed contract's verified code (and all dependencies) match the code in master
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [x] Governance proposal matches the deploy script
- [x] Smoke tests pass after fork test execution of the governance proposal

**Comment by DanielVF** [comment]
Test code.

```python
from world import *
FRXETH_REDEEM_STRAT = '0x95A8e45afCfBfEDd4A1d41836ED1897f3Ef40A9e'
frxeth_redeem_strat = load_contract('frxeth_redeem_strat', FRXETH_REDEEM_STRAT)

oeth_vault_admin.approveStrategy(FRXETH_REDEEM_STRAT, {'from': TIMELOCK})

oeth_vault_admin.withdrawAllFromStrategy(FRAX_ETH_STRATEGY, {'from': STRATEGIST})
print(frxeth.balanceOf(vault_oeth_core) / 1e18, weth.balanceOf(vault_oeth_core) / 1e18)

vault_oeth_admin.depositToStrategy(FRXETH_REDEEM_STRAT, [frxeth], [1003e18], {'from': STRATEGIST})
tickets = [int(x['data'][2:66],16) for x in history[-1].logs if x['address'] == FRXETH_REDEEM_STRAT and len(x['topics'])==1]
print(tickets)
print(frxeth.balanceOf(vault_oeth_core) / 1e18, weth.balanceOf(vault_oeth_core) / 1e18)
chain.sleep(16*24*3600)
frxeth_redeem_strat.redeemTickets(tickets, 1003e18, {'from': STRATEGIST})
print(frxeth.balanceOf(vault_oeth_core) / 1e18, weth.balanceOf(vault_oeth_core) / 1e18)
```

**Comment by DanielVF** [comment]
Sorry, @shahthepro - this will need a review of merge conflicts with master.

**Review by shahthepro — APPROVED** [review]
Checked merge commits, looks good to me. LGTM

**Pull request merged**
