### PR TITLE
fix: remove double IPFS and pull the logic to env variables

### PR DESCRIPTION
**Pull request by rafaelugolini**
If you made a contract change, make sure to complete the checklist below before merging it in master.

Refer to our [documentation](https://github.com/OriginProtocol/security) for more details about contract security best practices.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. 
  - [ ] Copy & paste code review [security checklist](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md) below this checklist.
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Review by shahthepro — APPROVED** [review]

**Comment by shahthepro** [comment]
Just wondering if this should be done in `oeth-dapp` branch instead

**Comment by rafaelugolini** [comment]
> Just wondering if this should be done in `oeth-dapp` branch instead

what do you mean? It's going to be merged there `oeth-dapp`

**Comment by shahthepro** [comment]
> > Just wondering if this should be done in `oeth-dapp` branch instead
> 
> what do you mean? It's going to be merged there `oeth-dapp`

Sorry, didn't check the base branch clearly 😅

**Review by shahthepro — APPROVED** [review]

**Review by smitch88 — APPROVED** [review]
LGTM ty

**Pull request merged**
