### PR TITLE
CompensationClaims contract deployment

### PR DESCRIPTION
**Pull request by franckc**

### CODE REVIEW

**Comment by franckc** [comment]
@sparrowDom I deployed the OUSD compensation claims contract to mainnet so we should now be able to test on the fork. The address of the contract is 0x9C94df9d594BA1eb94430C006c269C314B1A8281

A couple of things to note:
 - We ran into an issue verifying the contract's code on Etherscan on mainnet. @crazybuster is looking into that.
 - I have submitted a governance proposal (ID 11) to transfer governance of that contract from the deployer to the governor. The multi-sig signers haven't approved that proposal yet. Should hopefully happen tonight
 - The adjuster account was set to 0x71F78361537A6f7B6818e7A760c8bC0146D93f50
 - To call the adjuster on the fork, the easiest is to impersonate it. See an example here that impersonates the binance account: <https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/tasks/account.js#L63>

So overall for testing on fork, we should be able to do something like this on the branch of this PR (or on master once merged, feel free to merge if it looks good to you):
1. Start a fork in a terminal:
```
export PROVIDER_URL="https://eth-mainnet.alchemyapi.io/v2/6vvlq0..."
export BLOCK_NUMBER=<recent_block_number>
yarn run node:fork
```

2. In a separate terminal start a console
```
FORK=true npx hardhat console --network localhost
```
Then in the console:
- impersonate the governor
- unlock the adjuster
- impersonate the adjuster account
- call setClaims on the CompensationClaims contract
- lock the adjuster
- impersonate the users and for each of them call claim() on the contract
Alternatively all the above from step 2 could be done in a script.

Let me know any questions!

**Review by sparrowDom — COMMENTED** [review]
lgtm

**Comment by sparrowDom** [comment]
@franckc I got to the point where minting OUSD was needed. And couldn't get that part to work. Now that the contract ownership has been transferred to multisig the governor calls are not working anymore: 

```
const addresses = require('./utils/addresses');
const { BigNumber } = ethers
const { compensationSync } = require('./scripts/compensation/compensationSync');
const reimbursementsLocation = './scripts/staking/reimbursements.csv'

const compensationClaims = await ethers.getContractAt("CompensationClaims", addresses.mainnet.CompensationClaims)
const ousd = await ethers.getContractAt("OUSD", addresses.mainnet.OUSDProxy)
await hre.network.provider.request({ method: "hardhat_impersonateAccount", params: [addresses.mainnet.Binance]});
const binanceSigner = await hre.ethers.provider.getSigner(addresses.mainnet.Binance);

// impersonate governor
const governorAddress = '0x8e7bdfecd1164c46ad51b58e49a611f954d23377';
await hre.network.provider.request({ method: "hardhat_impersonateAccount", params: [governorAddress]});
const governorSigner = await hre.ethers.provider.getSigner(governorAddress);

// send governor contract some eth since it has 0 right now
await binanceSigner.sendTransaction({ to: governorAddress, value: ethers.utils.parseEther("100.0")});

const result = await compensationClaims.connect(governorSigner).unlockAdjuster()

// Check the current state of the compensation contract
compensationSync(compensationClaims, reimbursementsLocation, true, governorSigner)

const result1 = await compensationClaims.connect(governorSigner).lockAdjuster()


//// TRANSFER OUSD
const erc20Abi = require('./test/abi/erc20.json')
const usdt = await ethers.getContractAt(erc20Abi, addresses.mainnet.USDT);
const vaultAbi = require('./artifacts/contracts/interfaces/IVault.sol/IVault.json').abi
//const randomAddress = '0x17BAd8cbCDeC350958dF0Bfe01E284dd8Fec3fcD'
await hre.network.provider.request({ method: "hardhat_impersonateAccount", params: [randomAddress]});
const randomSigner = await hre.ethers.provider.getSigner(randomAddress);


const vault = await ethers.getContractAt(vaultAbi, addresses.mainnet.VaultProxy);

// await usdt.connect(binanceSigner).transfer(randomAddress, ethers.utils.parseUnits('10000000', 6))
//await usdt.connect(randomAddress).approve(vault.address, ethers.constants.MaxUint256)

// starts to fail here
await usdt.connect(binanceSigner).approve(vault.address, ethers.constants.MaxUint256)
const mintResult = await vault.connect(binanceSigner).mint(addresses.mainnet.USDT, ethers.utils.parseUnits('1696581', 6), BigNumber.from('0'))
//// END TRANSFER OUSD

await compensationClaims.connect(governorSigner).start(60*60*24*90)
```

**Comment by franckc** [comment]
@sparrowDom hmm. I don't see any obvious issue with your code snippet above. I did not have time to try to run. it myself tonight but I can spend time tomorrow helping.

**Comment by sparrowDom** [comment]
@franckc I've updated the above comment with the current state. Your fund & mint tasks really helped a lot. Everything above executes well now using `executeOnFork`.

**Pull request merged**
