### PR TITLE
Oeth dapp UI style fixes

### PR DESCRIPTION
**Pull request by smitch88**
**The following issues are addressed in this PR:**

[1498](https://github.com/OriginProtocol/origin-dollar/issues/1498)
* Fixed by setting the default `swapMode` to `mint` instead of `redeem`. `ETH` will now be the first currency shown

[1462](https://github.com/OriginProtocol/origin-dollar/issues/1462)
* Changes the APY dropdown to conform to the new dropdown menu styling
* Adds long text descriptions on the dropdown, 7d -> 7-day trailing
* Adjusts hover state color to match designs

Screenshot 2023-05-18 143709

[1464](https://github.com/OriginProtocol/origin-dollar/issues/1464)
* Adjusted the base size of the `Connect` button to 16px to be in line with the designs and other header items
* Verified it's using `Inter` font
Screenshot 2023-05-18 143735

[1474](https://github.com/OriginProtocol/origin-dollar/issues/1474)
* Added a property `inputMode` on the input elements for both swap and wrap. Brings up the numeric keypad on mobile instead of the alphabet
unnamed

[1466](https://github.com/OriginProtocol/origin-dollar/issues/1466)
* Fixed by auto setting `.` values into `0.` so it gets the user started on writing out the decimal
### Typing in "." first
OETH

[1477](https://github.com/OriginProtocol/origin-dollar/issues/1477)
* Removes the animation duration entirely

[1472](https://github.com/OriginProtocol/origin-dollar/issues/1472)
* Adds new component into the wrap home page, links out to `https://oeth.com`
Screenshot 2023-05-18 143913

[1496](https://github.com/OriginProtocol/origin-dollar/issues/1496)
* Removes OETH option from redeem coin set
Screenshot 2023-05-18 144750

[1488](https://github.com/OriginProtocol/origin-dollar/issues/1488)
[1485](https://github.com/OriginProtocol/origin-dollar/issues/1485)
* Fixes icon distortion, uploads svg icons as well to remove any pixelation

### CODE REVIEW

**Comment by matt-bullock** [comment]
@smitch88 you can go ahead and merge these. I left a couple of comments on the dropdown ticket but those shouldn't hold this back and they're very minor visual fixes

**Comment by smitch88** [comment]
> @smitch88 you can go ahead and merge these. I left a couple of comments on the dropdown ticket but those shouldn't hold this back as they're very minor visual fixes

Screenshot 2023-05-18 171818

Screenshot 2023-05-18 171810

**Review by matt-bullock — APPROVED** [review]

**Review by HrikB — APPROVED** [review]
Only thing I want to flag is that the double IPFS button is back on the heroku build since we didn't add the domain to that check. But not a huge deal since it's just a preview.

**Comment by shahthepro** [comment]
> Only thing I want to flag is that the double IPFS button is back on the heroku build since we didn't add the domain to that check. But not a huge deal since it's just a preview.

Let's get rid of the domain check. We have `DEPLOY_ENV=ipfs` env variable that we use at places. Can use the same here. We cannot keep updating the domain everytime there's a change in host. That just sounds hackish

**Comment by rafaelugolini** [comment]
> Only thing I want to flag is that the double IPFS button is back on the heroku build since we didn't add the domain to that check. But not a huge deal since it's just a preview.

heroku deployed is broken, I need to fix it. It's probably an ENV var that I will look at it today

**Pull request merged**
