### PR TITLE
introduce lastOverride global state to display prompt

### PR DESCRIPTION
**Pull request by jastroud**
Original issue: https://github.com/OriginProtocol/origin-dollar/issues/961

We prompt the users when they submit the transactions if (1) the default selection was overridden, (2) the input was changed after the initial warning was displayed, and (3) the current selection is different from the last override

I introduced a new global state (lastOverride) to save the last selection from the users and compare it with the best/current selection when they try to submit the transaction (approval) and based on the comparison result, display the confirmation modal.

### CODE REVIEW

**Comment by sparrowDom** [comment]
Screenshot 2022-06-09 at 10 25 01

Hey when testing I got this message even though I have not manually changed anything.

Also would be cool to reference the original issue in the PR description and add some description so that whoever checks this PR out knows what is going on.

**Comment by jastroud** [comment]
@sparrowDom My bad, I missed the case when lastOverride is undefined (first time). I updated the PR and you are good to review it again. Good catch, Thanks!

**Comment by sparrowDom** [comment]
Hey still having issues with this one. Now the prompt doesn't show up when it should. See behaviour here: 
https://www.loom.com/share/101f7b3b03144d56a04c1cafbb8bc320

**Comment by jastroud** [comment]
https://www.loom.com/share/5dff6bc062fa4678aa583e7bc2151f8f

@sparrowDom I am not able to replicate the issue on my local, above is what I am seeing on my end.
I think caches might cause the issue.

**Comment by rolandpo** [comment]
One minor thing is that if you switch contracts while the modal is shown then it becomes a bit confusing

Screenshot 2022-06-09 at 15 45 36

**Comment by jastroud** [comment]
Posting screenshots on various devices.

image
image
image

**Comment by jastroud** [comment]
@sparrowDom @rolandpo Updated the PR based on our discussion and agreement. You can review it again when you are available, Thanks!

**Review by sparrowDom — APPROVED** [review]
Nice job thanks!

**Pull request merged**
