### PR TITLE
fix: show error `reason` or `message` in bottom `SwapCurrencyPill`

### PR DESCRIPTION
**Pull request by apexearth**
Proposal to fix the stuck on 'Loading...' issue by showing the error seen in the calculation instead.

Screenshot 2023-09-07 at 1 47 19 PM

### CODE REVIEW

**Comment by apexearth** [comment]
FYI seems like my user chris@originprotocol.com on Heroku doesn't have access to the pipeline shown here.

**Review by toniocodo — APPROVED** [review]
LGTM, let's validate with Micah that he agrees with the error message location and styles, and good to go

**Comment by rafaelugolini** [comment]
> LGTM, let's validate with Micah that he agrees with the error message location and styles, and good to go

@apexearth can we get the price once it's below peg?

**Review by rafaelugolini — APPROVED** [review]

**Comment by apexearth** [comment]
> > LGTM, let's validate with Micah that he agrees with the error message location and styles, and good to go
> 
> @apexearth can we get the price once it's below peg?

Yeah this should start working once the price is within the proper bounds.

**Pull request merged**
