### PR TITLE
Deploy 66 - Upgrade OETH Vault with collateral swaps

### PR DESCRIPTION
**Pull request by naddison36**
| Contract | Address |
|--------|--------|
| OETHVaultCore | [0xEA24e9Bac006DE9635Ac7fA4D767fFb64FB5645c](https://etherscan.io/address/0xEA24e9Bac006DE9635Ac7fA4D767fFb64FB5645c#code) |
| OETHVaultAdmin | [0x31a91336414d3B955E494E7d485a6B06b55FC8fB](https://etherscan.io/address/0x31a91336414d3B955E494E7d485a6B06b55FC8fB#code) |

[Proposal ID: 54](https://etherscan.io/tx/0x10cc265d3fe0812cf19ff6d71a85a12ae8e08ac1592391f9f80d37a84d0cf476)

Dependant contracts deployed in 065 with PR https://github.com/OriginProtocol/origin-dollar/pull/1581

| Contract | Address |
|--------|--------|
| Swapper1InchV5 | [0xcD0fcF8a31Bc78ec07752e9CCD3960E936D18366](https://etherscan.io/address/0xcD0fcF8a31Bc78ec07752e9CCD3960E936D18366#code) |

```
INFO: Args: [
  [
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab",
    "0x39254033945AA2E4809Cc2977E7087BEE48bd7Ab"
  ],
  [
    "upgradeTo(address)",
    "setAdminImpl(address)",
    "setSwapper(address)",
    "cacheDecimals(address)",
    "cacheDecimals(address)",
    "cacheDecimals(address)",
    "cacheDecimals(address)",
    "setOracleSlippage(address,uint16)",
    "setOracleSlippage(address,uint16)",
    "setOracleSlippage(address,uint16)",
    "setOracleSlippage(address,uint16)",
    "setSwapAllowedUndervalue(uint16)"
  ],
  [
    "0x000000000000000000000000ea24e9bac006de9635ac7fa4d767ffb64fb5645c",
    "0x00000000000000000000000031a91336414d3b955e494e7d485a6b06b55fc8fb",
    "0x000000000000000000000000cd0fcf8a31bc78ec07752e9ccd3960e936d18366",
    "0x000000000000000000000000ae78736cd615f374d3085123a210448e74fc6393",
    "0x000000000000000000000000ae7ab96520de3a18e5e111b5eaab095312d7fe84",
    "0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    "0x0000000000000000000000005e8422345238f34275888049021821e8e08caa1f",
    "0x000000000000000000000000ae78736cd615f374d3085123a210448e74fc639300000000000000000000000000000000000000000000000000000000000000c8",
    "0x000000000000000000000000ae7ab96520de3a18e5e111b5eaab095312d7fe840000000000000000000000000000000000000000000000000000000000000046",
    "0x000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000000000014",
    "0x0000000000000000000000005e8422345238f34275888049021821e8e08caa1f0000000000000000000000000000000000000000000000000000000000000014",
    "0x0000000000000000000000000000000000000000000000000000000000000032"
  ]
]
```

### CODE REVIEW

**Review by shahthepro — COMMENTED** [review]
LGTM

Comments:
- Swapper is deployed from a [different deployment file (that has no governance action)](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/deploy/065_oeth_swapper.js) but not listed on this PR. However, it is verified on Etherscan (Yet to verify the deployed bytecode though)

Checklist:
- [ ] All deployed contracts are listed in the deploy PR's description (Swapper is missing)
- [x] Deployed contract's verified code (and all dependencies) match the code in master
- [x] The transactions that interacted with the newly deployed contract match the deploy script
- [x] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal

**Comment by DanielVF** [comment]
Review in progress...

- [x] All deployed contracts are listed in the deploy PR's description
    - Swap contract deploy was a part of a previous PR
- [ ] Deployed contract's verified code (and all dependencies) match the code in master
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal

**Comment by sparrowDom** [comment]
Checklist:
- [x] All deployed contracts are listed in the deploy PR's description
- [x] Deployed contract's verified code (and all dependencies) match the code in master
  - VaultAdmin + VaultCore's code and all imports are a match ✅ 
  - As Daniel points out swapper has some require statements deployed that are missing from master:  
Screenshot 2023-06-27 at 12 10 55. 
- [x] The transactions that interacted with the newly deployed contract match the deploy script
- [x] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal

**Review by sparrowDom — APPROVED** [review]

**Comment by sparrowDom** [comment]
I've used this script for fork testing: 
```
from world import *
from collateralSwap import *


test_cases = [
	# from, to, amount_from, min_expected_amount
	[ weth, reth, 10 * 10**18, 9.28 * 10**18],
	[ weth, frxeth, 10 * 10**18, 9.28 * 10**18],
	[ weth, steth, 10 * 10**18, 9.9 * 10**18],
	[ reth, weth, 10 * 10**18, 10.73 * 10**18],
	[ reth, frxeth, 10 * 10**18, 10.73 * 10**18],
	[ reth, steth, 10 * 10**18, 10.65 * 10**18],
	[ steth, reth, 10 * 10**18, 9.12 * 10**18],
	[ steth, weth, 10 * 10**18, 9.82 * 10**18],
	[ steth, frxeth, 10 * 10**18, 9.82 * 10**18],
	[ frxeth, steth, 10 * 10**18, 9.88 * 10**18],
	[ frxeth, reth, 10 * 10**18, 9.26 * 10**18],
	[ frxeth, weth, 10 * 10**18, 9.96 * 10**18]
]

FRX_FINANCE = "0xac3e018457b222d93114458476f3e3416abbe38f"
# lets get some fraxEth to the vault
frxeth.transfer(oeth_vault_admin.address, 500 * 10**18, {"from": FRX_FINANCE})

for test_case in test_cases:
	from_token = test_case[0]
	to_token = test_case[1]
	amount_from = test_case[2]
	min_to_expected = test_case[3]

	with TemporaryFork():
		from_balance_before = from_token.balanceOf(vault_oeth_admin)
		to_balance_before = to_token.balanceOf(vault_oeth_admin)

		try:
			to, data = build_swap_tx(from_token.address, to_token.address, amount_from, 1, False)
			sig, args = vault_oeth_admin.decode_input(data)
			oeth_vault_admin.swapCollateral(*args, std)
		except Exception as e:
			print("❌ Test case: {} failed with error: {}".format(test_case, str(e)))

		from_balance_diff = from_balance_before - from_token.balanceOf(vault_oeth_admin)
		to_balance_diff = to_token.balanceOf(vault_oeth_admin) - to_balance_before

		if to_balance_diff >= min_to_expected:
			print("✅ swap ok")
		else:
			print("❌ swap not ok")

```
and some of the swaps fail with the error: 
Screenshot 2023-06-27 at 17 52 12

Seems that 1inch returned a swap selector our code is not prepared for. See example of 1inch swap endpoint return: 
```
{'fromToken': {'symbol': 'WETH', 'name': 'Wrapped Ether', 'address': '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'decimals': 18, 'logoURI': 'https://tokens.1inch.io/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2.png', 'wrappedNative': True, 'tags': ['tokens', 'PEG:ETH']}, 'toToken': {'symbol': 'rETH', 'name': 'Rocket Pool ETH', 'decimals': 18, 'address': '0xae78736cd615f374d3085123a210448e74fc6393', 'logoURI': 'https://tokens.1inch.io/0xae78736cd615f374d3085123a210448e74fc6393.png', 'tags': ['tokens']}, 'toTokenAmount': '9295273806569826806', 'fromTokenAmount': '10000000000000000000', 'protocols': [[[{'name': 'UNISWAP_V3', 'part': 100, 'fromTokenAddress': '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', 'toTokenAddress': '0xae78736cd615f374d3085123a210448e74fc6393'}]]], 'tx': {'from': '0xcD0fcF8a31Bc78ec07752e9CCD3960E936D18366', 'to': '0x1111111254eeb25477b68fb85ed929f73a960582', 'data': '0xe449022e0000000000000000000000000000000000000000000000008ac7230489e800000000000000000000000000000000000000000000000000007fb536417d481c1900000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000001800000000000000000000000a4e0faa58465a2d369aa21b3e42d43374c6f9613cfee7c08', 'value': '0', 'gas': 0, 'gasPrice': '26775520955'}}
```
you can see that the selector in the data is 0xe449022e
and from this github page where someone built a plugin for 1inch ( https://github.com/LedgerHQ/app-plugin-1inch )
seems like the selector is for the function: uniswapV3Swap

**Review by sparrowDom — CHANGES_REQUESTED** [review]
Changing to request change, since it might mean we need to re-deploy the collateral swapper

**Comment by naddison36** [comment]
The off-chain component that calls the 1Inch swap API needs to set the `fromAddress` param to the swapper contract and the `destReceiver` needs to be the vault. At the moment they are both the swapper contract which means the `uniswapV3Swap` function is being called on the 1Inch router instead of `uniswapV3SwapTo`.

**Review by sparrowDom — APPROVED** [review]
as @naddison36 figured it out, there was a missing `destReceiver` in my offline swap module that was causing the use of unwanted selector. All the fork tests with the above posted script now pass. 

Amazing work Nick, LGTM

**Review by DanielVF — APPROVED** [review]

**Pull request merged**
