### PR TITLE
Deploy 48 - Vault direct reallocations

### PR DESCRIPTION
**Pull request by sparrowDom**
Deploys new implementation of vaultAdmin, proposal id #44

### CODE REVIEW

**Review by franckc — APPROVED** [review]
LGTM

**Review by shahthepro — APPROVED** [review]
- [x] Deployed contract verified code (and dependancies) match the final PR commit's code
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [x] Governance proposal matches the deploy script
- [x] Fork tests pass
- [ ] Smoke tests pass after fork test execution of the governance proposal

**Comment by DanielVF** [comment]
- [x] Deployed contract verified code (and dependancies) match the final PR commit's code
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script
- [x] Smoke tests pass after fork test execution of the governance proposal

**Comment by DanielVF** [comment]
Will create governance proposal in new system.

**Pull request merged**
