### PR TITLE
Deploy 043 - OUSD Metastrategy

### PR DESCRIPTION
**Pull request by sparrowDom**
Deploy for #1002 MetaStrategy

Deployed contracts:

- OUSD Metastrategy Proxy: [0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90](https://etherscan.io/address/0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90)
- OUSD Metastrategy: [0xc7faB3de576caf6044369930422f12C4FDbb2B32](https://etherscan.io/address/0xc7faB3de576caf6044369930422f12C4FDbb2B32)
- Vault Core: [0x997c35A0bf8E21404aE4379841E0603C957138c3](https://etherscan.io/address/0x997c35A0bf8E21404aE4379841E0603C957138c3)
- Vault Admin: [0xb981226900B63c4dB67E3e80C56Ff4b9f9135Ad0](https://etherscan.io/address/0xb981226900B63c4dB67E3e80C56Ff4b9f9135Ad0)

Governance proposal 38.

---

Please verify that:

- [ ] Deployed contract verified code (and dependancies) match the final PR commit's code
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal

### CODE REVIEW

**Comment by sparrowDom** [comment]
@DanielVF Ahh I see my bad when verifying source code I ran: 
```
npx hardhat --network mainnet verify --contract contracts/proxies/Proxies.sol:ConvexUSDDMetaStrategyProxy 0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90
```
instead of 
```
npx hardhat --network mainnet verify --contract contracts/proxies/Proxies.sol:ConvexOUSDMetaStrategyProxy 0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90
```

**Comment by sparrowDom** [comment]
Seems source code [can not be re-verified](https://ethereum.stackexchange.com/questions/40186/possible-to-change-etherscan-verified-source-after-initially-verified). You think this is something we want to kick off again and correct?

**Comment by DanielVF** [comment]
I've done it myself. Not worth a redo of everything. Good to know how it happened.

**Comment by DanielVF** [comment]
Verified that:

- [ ] Deployed contract verified code (and dependancies) match the final PR commit's code (_still working on it_)
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [x] Governance proposal matches the deploy script
- [x] Smoke tests pass after fork test execution of the governance proposal


Smoke test:

```python
>>> from world import *
>>> sim_governor_execute(38)
>>> META_STRAT = '0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90'

>>> c18(vault_core.totalValue())
c18(ousd.totalSupply())
'      44,953,957'
>>> c18(ousd.totalSupply())
'      44,953,199'
>>> c18(ousd.totalSupply()-ousd.nonRebasingSupply())
'      18,834,773'
>>>
>>> vault_admin.reallocate(COMP_STRAT, META_STRAT, [USDC], [1e6 * 1e6], {'from': STRATEGIST})
>>> c18(vault_core.totalValue())
'      46,953,825'
>>> c18(ousd.totalSupply())
'      46,953,793'
>>> c18(ousd.totalSupply()-ousd.nonRebasingSupply())
'      18,835,407'
>>>
>>> vault_admin.withdrawAllFromStrategy(META_STRAT, {'from': STRATEGIST})
>>> c18(vault_core.totalValue())
'      45,471,976'
>>> c18(ousd.totalSupply())
'      45,471,975'
>>> c18(ousd.totalSupply()-ousd.nonRebasingSupply())
'      18,835,438'
```

**Comment by micahalcorn** [comment]
> @DanielVF Ahh I see my bad when verifying source code I ran:
> 
> ```
> npx hardhat --network mainnet verify --contract contracts/proxies/Proxies.sol:ConvexUSDDMetaStrategyProxy 0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90
> ```

Was this just a copy/paste issue or do we have a USDD strategy ready to go?

**Comment by sparrowDom** [comment]
@micahalcorn this was a copy paste issue. In the codebase we have 4 example migrations + proxy contracts of stablecoins that Derek has suggested some time ago. And my mistake was copying the wrong one from the list of options.

**Comment by sparrowDom** [comment]
@DanielVF one cool thing (seen in this PR as well) is that now we can add `proposalId` to deploy script and instead of deploying the fork tests check if the proposal is in `New` or `Queued` state and executes the proposal. And then the fork tests are ran on top of that. 
So we could also implement the above brownie smoke test in for test environment and have it run always as part of the CI.

**Comment by DanielVF** [comment]
I fork tested harvesting, which appears to work.

**Comment by DanielVF** [comment]
I notice that the netOusdMintForStrategyThreshold is set to 50 million. Given that this parameter is a safety parameter in case something goes wrong, I would have expected it to launch with a small value that we then increase over time. 

It's probably less critical on the transfer of funds in now that minting OUSD maxes out at 2x the transfer amount, but we should probably lower it somewhat afterwards the initial funds move today.

**Comment by shahthepro** [comment]
- [x] ~~Deployed contract verified code (and dependancies) match the final PR commit's code~~ (Checked the bytecode against the deployed contracts)
- [x] ~~The transactions that interacted with the newly deployed contract match the deploy script~~ (Order of transactions and params do match)
- [x] ~~Governance proposal matches the deploy script~~ (Actions and params match, proposal runs fine on fork)
- [ ] ~~Smoke tests pass after fork test execution of the governance proposal~~ (Seems fine when interacting with the Vault directly with brownie on the fork but fork-tests fail locally and on CI)

**Review by DanielVF — APPROVED** [review]

**Comment by sparrowDom** [comment]
[WaitForTransaction](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/utils/deploy.js#L81) fails when deploying VaultAdmin of the deployment after 043 OUSD Metastrategy deploy goes through. 

Will investigate further if fork tests still fail after we execute the proposal.

**Pull request merged**
