### PR TITLE
Strategist runlogs to March 3

### PR DESCRIPTION
**Pull request by DanielVF**

### CODE REVIEW

**Review by sparrowDom — APPROVED** [review]
lgtm

**Comment by DanielVF** [comment]
Just wanted to highlight these changes to make vault held funds a part of the allocation calcs, as well as the change to use the current dollar amount of core stables in the meta strategy

image

**Comment by DanielVF** [comment]
UI bug is preventing this PR from merging. Will close it, then reopen, then try merge.

**Comment by DanielVF** [comment]
Ugh. Well, I had to do dark git magic to squash everything to a single verified commit.

**Pull request merged**
