### PR TITLE
Deploy 080 - Add OETH Buyback and upgrade OUSD Buyback

### PR DESCRIPTION
**Pull request by shahthepro**
Deployment file: `080_upgrade_buyback.js`

Deployed contracts:

| Contract name | Address |
| --------------- | -------- |
| OETHBuybackProxy (new) | [0xfd6c58850cacf9ccf6e8aee479bfb4df14a362d2](https://etherscan.io/address/0xfd6c58850cacf9ccf6e8aee479bfb4df14a362d2) |
| OETHBuyback (new) | [0x6F2733a7dEE9C7456227576262d8339b82BBEe8F](https://etherscan.io/address/0x6F2733a7dEE9C7456227576262d8339b82BBEe8F) |
| OUSDBuyback (upgraded) | [0xB06d8C94D4073E249fDEc446b1A99a2f5F482A20](https://etherscan.io/address/0xB06d8C94D4073E249fDEc446b1A99a2f5F482A20) |

Other addresses:

| Name | Address |
| ------ | -------- |
| Deployer | [0x58890a9cb27586e83cb51d2d26bbe18a1a647245](https://etherscan.io/address/0x58890a9cb27586e83cb51d2d26bbe18a1a647245) |
| Proposer | [0x6a6D776120f7e4a8dba5F6bF49b85cb340Cfe241](https://etherscan.io/address/0x6a6D776120f7e4a8dba5F6bF49b85cb340Cfe241) |

Governance Proposal:

| | |
| - | - |
| Proposal ID | [106657143654146782218499766782185241541410736110675785019130125273133364011619](https://governance.ousd.com/proposals/106657143654146782218499766782185241541410736110675785019130125273133364011619) |
| Proposal Tx | [0xccae08ab791462d716733648825fd9684e4d22d234cd277517942c512ffd931d](https://etherscan.io/tx/0xccae08ab791462d716733648825fd9684e4d22d234cd277517942c512ffd931d) |

Proposal Actions:
- Upgrades existing BuybackProxy to use the deployed `OUSDBuyback` implementation
- Sets the Router address to Uniswap's Universal Router address on `OUSDBuybackProxy`
- Resets allowance on `OUSDBuybackProxy` for `CVXLocker`
- Sets the trustee address on OETH Vault to delpoyed `OETHBuybackProxy` (to receive fees)
- Resets allowance on `OETHBuybackProxy` for `CVXLocker`
- Transfers leftover OUSD from older buyback contracts to `OUSDBuyback` (through Governor)

----------

Some things to verify (when reviewing):
- [x] Deployment proposal matches the deploy script
- [x] Contracts are verified on Etherscan
- [x] Deployed bytecode matches code on `master`
- [x] Check the addresses in constructor and on the proposal
   - [x] Uniswap's Universal Router
   - [x] CVX Locker
   - [x] CVX
   - [x] OGV
 - [x] All OUSD is moved from older buyback contracts to the correct one
- [x] Fork tests pass on CI (with proposalId set)

### CODE REVIEW

**Comment by naddison36** [comment]
The contract code on the `shah/deploy_080` branch matches the deployed contracts

```
sol2uml diff 0xFD6c58850caCF9cCF6e8Aee479BFb4Df14a362D2 .,node_modules
Compared the "OETHBuybackProxy" contract with address 0xFD6c58850caCF9cCF6e8Aee479BFb4Df14a362D2 on mainnet
to local files under folders ".,node_modules"

match   @openzeppelin/contracts/utils/Address.sol
match   contracts/governance/Governable.sol
match   contracts/proxies/InitializeGovernedUpgradeabilityProxy.sol
match   contracts/proxies/Proxies.sol
```

```
sol2uml diff 0x6F2733a7dEE9C7456227576262d8339b82BBEe8F .,node_modules
Compared the "OETHBuyback" contract with address 0x6F2733a7dEE9C7456227576262d8339b82BBEe8F on mainnet
to local files under folders ".,node_modules"

match   @openzeppelin/contracts/token/ERC20/IERC20.sol
match   @openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol
match   @openzeppelin/contracts/utils/Address.sol
match   contracts/buyback/BaseBuyback.sol
match   contracts/buyback/OETHBuyback.sol
match   contracts/governance/Governable.sol
match   contracts/governance/Strategizable.sol
match   contracts/interfaces/chainlink/AggregatorV3Interface.sol
match   contracts/interfaces/ICVXLocker.sol
match   contracts/interfaces/IUniswapUniversalRouter.sol
match   contracts/utils/Initializable.sol
```

```
sol2uml diff 0xB06d8C94D4073E249fDEc446b1A99a2f5F482A20 .,node_modules
Compared the "OUSDBuyback" contract with address 0xB06d8C94D4073E249fDEc446b1A99a2f5F482A20 on mainnet
to local files under folders ".,node_modules"

match   @openzeppelin/contracts/token/ERC20/IERC20.sol
match   @openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol
match   @openzeppelin/contracts/utils/Address.sol
match   contracts/buyback/BaseBuyback.sol
match   contracts/buyback/OUSDBuyback.sol
match   contracts/governance/Governable.sol
match   contracts/governance/Strategizable.sol
match   contracts/interfaces/chainlink/AggregatorV3Interface.sol
match   contracts/interfaces/ICVXLocker.sol
match   contracts/interfaces/IUniswapUniversalRouter.sol
match   contracts/utils/Initializable.sol
```

**Comment by naddison36** [comment]
I've verified that:

- the contract code on the `shah/deploy_080` branch matches the deployed contracts
- the constants and immutables in the deployed contracts are correct
- ran buy back fork tests locally
- checked storage slots for upgraded OUSD Buy Back
- the actions in the proposal match the `080_upgrade_buyback` script and the addresses are correct

**Comment by DanielVF** [comment]
(Still in progress)

- [x] All deployed contracts are listed in the deploy PR's description
- [x] Deployed contract's verified code (and all dependencies) match the code in master
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [ ] Governance proposal matches the deploy script
- [ ] Smoke tests pass after fork test execution of the governance proposal

### Deployed code matches
```
~/.bin/ousd_contract_changes.fish 0xfd6c58850cacf9ccf6e8aee479bfb4df14a362d2
>> ./contracts/governance/Governable.sol
>> ./contracts/proxies/Proxies.sol
>> ./contracts/proxies/InitializeGovernedUpgradeabilityProxy.sol
>> ./@openzeppelin/contracts/utils/Address.sol

~/.bin/ousd_contract_changes.fish 0x6F2733a7dEE9C7456227576262d8339b82BBEe8F
>> ./contracts/utils/Initializable.sol
>> ./contracts/buyback/OETHBuyback.sol
>> ./contracts/buyback/BaseBuyback.sol
>> ./contracts/governance/Governable.sol
>> ./contracts/governance/Strategizable.sol
>> ./contracts/interfaces/ICVXLocker.sol
>> ./contracts/interfaces/IUniswapUniversalRouter.sol
>> ./contracts/interfaces/chainlink/AggregatorV3Interface.sol
>> ./@openzeppelin/contracts/token/ERC20/IERC20.sol
>> ./@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol
>> ./@openzeppelin/contracts/utils/Address.sol

~/.bin/ousd_contract_changes.fish 0xB06d8C94D4073E249fDEc446b1A99a2f5F482A20
>> ./contracts/utils/Initializable.sol
>> ./contracts/buyback/OUSDBuyback.sol
>> ./contracts/buyback/BaseBuyback.sol
>> ./contracts/governance/Governable.sol
>> ./contracts/governance/Strategizable.sol
>> ./contracts/interfaces/ICVXLocker.sol
>> ./contracts/interfaces/IUniswapUniversalRouter.sol
>> ./contracts/interfaces/chainlink/AggregatorV3Interface.sol
>> ./@openzeppelin/contracts/token/ERC20/IERC20.sol
>> ./@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol
>> ./@openzeppelin/contracts/utils/Address.sol
```

### Initialize matches expected
```bash
cast --abi-decode --input "initialize(address,address,address,address)" 000000000000000000000000ef1c6e67703c7bd7107eed8303fbe6ec2554bf6b000000000000000000000000f14bbdf064e3f67f51cd9bd646ae3716ad938fdc000000000000000000000000f14bbdf064e3f67f51cd9bd646ae3716ad938fdc0000000000000000000000007d82e86cf1496f9485a8ea04012afeb3c7489397
0xEf1c6E67703c7BD7107eed8303Fbe6EC2554BF6B # Uniswap
0xF14BBdf064E3F67f51cd9BD646aE3716aD938FDC # Strategist
0xF14BBdf064E3F67f51cd9BD646aE3716aD938FDC # Strategist
0x7d82E86CF1496f9485a8ea04012afeb3C7489397 # Rewards
```

**Review by DanielVF — APPROVED** [review]
Completed the deploy checklist, notes above.

Thanks for the very clear description block on this, @shahthepro. Makes it very easy to work from for verifying.

**Pull request merged**
