### PR TITLE
1#658#752

### PR DESCRIPTION
**Pull request by Michael1104Smith**
Max Including Dust #652
Error Message Placement #658
APY Discrepancy #752

### CODE REVIEW

**Comment by Michael1104Smith** [comment]
You can check latest branch, 1#658#752.
Thank you.

**Comment by franckc** [comment]
@sparrowDom Do you mind reviewing this PR?

**Comment by sparrowDom** [comment]
Hey @Michael1104Smith just checking in. A lot of good work has already been done on these issue. Were you planning on completing the PR?

**Comment by sparrowDom** [comment]
closing as this has no activity.

**Pull request closed without merging**
