### PR TITLE
Default to placing AAVE in DAI

### PR DESCRIPTION
**Pull request by DanielVF**
Per this [community snapshot proposal ](https://vote.originprotocol.com/#/proposal/QmTzUJADm4XNFyoUQAAVpwzsWm1wQT8Q49uCvNAkdRYAJX) we are ready to move to using AAVE as our DAI default. 

This proposal sets AAVE to be the default DAI AAVE strategy that mints/redeems will come in and out of.

This also moves 8 million of the 8.6 million DAI we currently have on Compound over to AAVE. The entire amount is not moved since we must specify an exact amount to transfer, unless we were to pull everything out of Compound (USDT and USDC) as well and reinvest. By doing less than the full amount, we ensure this governance proposal succeeds.

We can do a later strategist action to move the remaining DAI.

### CODE REVIEW

**Review by franckc — APPROVED** [review]
LGTM

**Comment by DanielVF** [comment]
I've gone ahead and submitted this proposal as well:

```
Running 028_dai_default_aave deployment...
INFO: Sending proposal to governor...
INFO: Submitting proposal for Default DAI to AAVE Strategy to governor 0x72426BA137DEC62657306b12B1E869d43FeC6eC7
INFO: Args: [
  [
    "0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70",
    "0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70"
  ],
  [
    "setAssetDefaultStrategy(address,address)",
    "reallocate(address,address,address[],uint256[])"
  ],
  [
    "0x0000000000000000000000006b175474e89094c44da98b954eedeac495271d0f0000000000000000000000005e3646a1db86993f73e6b74a57d8640b69f7e259",
    "0x0000000000000000000000009c459eeb3fa179a40329b81c1635525e9a0ef0940000000000000000000000005e3646a1db86993f73e6b74a57d8640b69f7e259000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000010000000000000000000000006b175474e89094c44da98b954eedeac495271d0f0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000069e10de76676d08000000"
  ]
]
Gas price (gwei): Regular=153.844743508 Premium=175.383007599
INFO: Submitted proposal 9
INFO: Next step: call the following methods on the governor at 0x72426BA137DEC62657306b12B1E869d43FeC6eC7 via multi-sig
INFO:    queue(9)
INFO:    execute(9)
INFO: Done
INFO: Proposal sent.
028_dai_default_aave deploy done.
```

**Comment by franckc** [comment]
@tomlinton Does this look good to you? If yes we'll merge and get that proposal executed... :)

**Review by tomlinton — APPROVED** [review]

**Comment by tomlinton** [comment]
Looks good!

**Comment by DanielVF** [comment]
@franckc We are good for execution then.

**Pull request merged**
