### PR TITLE
Swap Route

### PR DESCRIPTION
**Pull request by HrikB**

### CODE REVIEW

**Review by rafaelugolini — CHANGES_REQUESTED** [review]
There is a CSS issue reported by @micahalcorn 
https://discord.com/channels/404673842007506945/1101138394706350220/1106057220543746079

**Comment by rafaelugolini** [comment]
@HrikB did you fix the header? This is on the latest fleek deploy

image

**Comment by HrikB** [comment]
Yup... header is fixed

**Comment by rafaelugolini** [comment]
> @HrikB it doesn't look fixed: https://www.loom.com/share/efec5977ade74a5dbded9a26d31195f9

I sync with @matt-bullock and only the wrap page needs fixing

**Review by rafaelugolini — APPROVED** [review]

**Pull request merged**
