### PR TITLE
Deprecate old balances and add reset function

### PR DESCRIPTION
**Pull request by tomlinton**
If you made a contract change, make sure to complete the checklist below before merging it in master.

Refer to our [documentation](https://github.com/OriginProtocol/security) for more details about contract security best practices.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass (not automated, run manually on local)

### CODE REVIEW

**Comment by DanielVF** [comment]
Reset function should probably disable itself after one run, even if it is only temporary.

**Comment by tomlinton** [comment]
I was thinking i'd deploy two copies and do:

- Upgrade to this
- Call reset
- Upgrade to the other copy that doesn't have the reset

In one transaction.

**Comment by franckc** [comment]
+1 for this approach.

**Comment by DanielVF** [comment]
Just as long as we are sure it's gone before going live!

**Pull request closed without merging**
