### PR TITLE
[H03] Incorrect slippage in Curve 3Pool strategy

### PR DESCRIPTION
**Pull request by tomlinton**
Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. See [template](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review.md) and [example](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md).
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Review by franckc — APPROVED** [review]
LGTM

**Comment by DanielVF** [comment]
I'm going to fork sim this one.

**Comment by tomlinton** [comment]
Here's my results of a reallocate of 1m from Compound to 3pool, and then a reallocate of the same amount back:

```
Vault value 25332707.790196806
Compound USDT 11373116.923125
Compound DAI 7821428.799414751
Compound USDC 6005765.846339
ThreePool USDT 0.0
ThreePool DAI 0.0

Vault value 25332582.754567005
Compound USDT 10658337.809716
Compound DAI 7821428.799414751
Compound USDC 6005765.846339
ThreePool USDT 203734.737617
ThreePool DAI 147464.78097519797
ThreePool USDC 363454.428235
````

**Comment by tomlinton** [comment]
Brownie script if it is useful:

```
from world import *
from brownie import Contract


def main():
    brownie.network.web3.provider.make_request("hardhat_impersonateAccount", [BINANCE])
    brownie.network.web3.provider.make_request("hardhat_impersonateAccount", [GOVERNOR])

    # Deploy 3pool
    threepoolStrategy = accounts[0].deploy(ThreePoolStrategy)
    threepoolStrategy.initialize(
        THREEPOOL,
        vault.address,
        CRV,
        [DAI, USDC, USDT],
        [THREEPOOL_TOKEN, THREEPOOL_TOKEN, THREEPOOL_TOKEN],
        THREEPOOL_GAUGE,
        THREEPOOL_MINTER,
    )

    # Setup 3pool
    vault.approveStrategy(threepoolStrategy.address, {"from": GOVERNOR})

    print("Vault value {}".format(vault.totalValue() / 1e18))
    print("Compound USDT {}".format(compoundStrategy.checkBalance(USDT) / 1e6))
    print("Compound DAI {}".format(compoundStrategy.checkBalance(DAI) / 1e18))
    print("Compound USDC {}".format(compoundStrategy.checkBalance(USDC) / 1e6))
    print("ThreePool USDT {}".format(threepoolStrategy.checkBalance(USDT) / 1e6))
    print("ThreePool DAI {}".format(threepoolStrategy.checkBalance(DAI) / 1e18))
    print("ThreePool USDC {}".format(threepoolStrategy.checkBalance(USDC) / 1e6))

    # Reallocate all Compound strategy USDC to 3pool strategy
    vault.reallocate(
        compoundStrategy.address,
        threepoolStrategy.address,
        [USDT],
        [1000000 * 1e6],
        {"from": GOVERNOR},
    )

    # Reallocate 3pool "virtual" USDT back to Compound
    vault.reallocate(
        threepoolStrategy.address,
        compoundStrategy.address,
        [USDT],
        [threepoolStrategy.checkBalance(USDT)],
        {"from": GOVERNOR},
    )

    print("Vault value {}".format(vault.totalValue() / 1e18))
    print("Compound USDT {}".format(compoundStrategy.checkBalance(USDT) / 1e6))
    print("Compound DAI {}".format(compoundStrategy.checkBalance(DAI) / 1e18))
    print("Compound USDC {}".format(compoundStrategy.checkBalance(USDC) / 1e6))
    print("ThreePool USDT {}".format(threepoolStrategy.checkBalance(USDT) / 1e6))
    print("ThreePool DAI {}".format(threepoolStrategy.checkBalance(DAI) / 1e18))
    print("ThreePool USDC {}".format(threepoolStrategy.checkBalance(USDC) / 1e6))
```

**Comment by tomlinton** [comment]
#718 removes the need for this PR.

**Review by DanielVF — APPROVED** [review]

**Pull request merged**
