### PR TITLE
🥏 [M05] Excessive withdrawal from 3pool Strategy

### PR DESCRIPTION
**Pull request by tomlinton**
Uses the Curve remove_liquidity_imbalance function to withdraw only whats necessary and calculates the maximum burn of the LP token by taking the worst case withdrawal scenario (all of one coin) in proportion to the amount we are withdrawing.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. See [template](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review.md) and [example](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md).
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Review by franckc — APPROVED** [review]
LGTM though this caused a unit test failure so please make sure that test did not actually catch a bug before merging...

**Comment by DanielVF** [comment]
We just need make the mocks work, and life is good. This is way better.

**Comment by tomlinton** [comment]
My bad, added it to the mock, we all still happy here? :)

**Comment by franckc** [comment]
Thanks for fixing that mock. LGTM

**Review by DanielVF — APPROVED** [review]

**Pull request merged**
