### PR TITLE
🥏 [N12] Unused variable

### PR DESCRIPTION
**Pull request by tomlinton**
Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. See [template](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review.md) and [example](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md).
  - [x] Unit tests pass
  - [x] Slither tests pass with no warning
  - [x] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Review by DanielVF — CHANGES_REQUESTED** [review]
@tomlinton This is only used by the UI. I don't think this method currently has a unit test. We should probably have one test just to keep ourselves sane, and not accidentally break the UI on a contract change.

**Comment by tomlinton** [comment]
Added ✅

**Review by DanielVF — APPROVED** [review]

**Comment by DanielVF** [comment]
@franckc Would you take a peak at this one? Thanks!

**Review by franckc — APPROVED** [review]
LGTM

**Pull request merged**
