### PR TITLE
Deploy 47 - Morpho Aave strategy

### PR DESCRIPTION
**Pull request by shahthepro**
Related PR: #1207 

Deployed contracts:

|Name|Address|
|------|------|
| MorphoAaveStrategy| [0xC72bda59E382be10bb5D71aBd01Ecc65aa16fD83](https://etherscan.io/address/0xC72bda59E382be10bb5D71aBd01Ecc65aa16fD83)|
| MorphoAaveStrategyProxy| [0x79F2188EF9350A1dC11A062cca0abE90684b0197](https://etherscan.io/address/0x79F2188EF9350A1dC11A062cca0abE90684b0197)|

~~Governance Proposal ID: [42](https://etherscan.io/tx/0x8169db0b039305df49e3709d7975b85e9c5ddda8586e1d9d0cbe0c670297c6e6)~~ **To be Cancelled**

Governance Proposal ID: [43](https://etherscan.io/tx/0xb49cf0aec3d3d2df16106afe7846be90983b78a27eacc1dbd44a2a72e57e47a8)

Note: Had to change `MAINNET_DEPLOYER` in hardhat.config.js file to an address that I have access to before I could run the deployment. Since the governance is transferred anyway, I believe the deployer address should have no significance. 

-----------------
If you made a contract change, make sure to complete the checklist below before merging it in master.

Refer to our [documentation](https://github.com/OriginProtocol/security) for more details about contract security best practices.

Contract change checklist:
  - [ ] Code reviewed by 2 reviewers. 
  - [ ] Copy & paste code review [security checklist](https://github.com/OriginProtocol/security/blob/master/templates/Contract-Code-Review-Example.md) below this checklist.
  - [ ] Unit tests pass
  - [ ] Slither tests pass with no warning
  - [ ] Echidna tests pass if PR includes changes to OUSD contract (not automated, run manually on local)

### CODE REVIEW

**Comment by DanielVF** [comment]
Yes, I have to change `MAINNET_DEPLOYER` for each deployment that I make.

**Comment by DanielVF** [comment]
- [ ] Deployed contract verified code (and dependancies) match the final PR commit's code
- [ ] The transactions that interacted with the newly deployed contract match the deploy script.
- [x] Governance proposal matches the deploy script
- [x] Smoke tests pass after fork test execution of the governance proposal
- [ ] Update Docs

### Deployed contract matches

🟥 The proxy source code is not verified yet. 0xa97F983EEaa74B92a6475c71838D04238DDA394D

### Governance Proposal

```python
from world import *
v = governor.getActions(41)
[print(v[0][i],v[1][i],v[2][i],) for i in range(0, len(v)+1)]
```

### Smoke Tests

```python
from world import *

MORPHO_AAVE_STRAT = '0xa97f983eeaa74b92a6475c71838d04238dda394d'
sim_governor_execute(42)

# -----

before = vault_core.totalValue()
vault_admin.reallocate(MORPHO_COMP_STRAT, MORPHO_AAVE_STRAT, [USDC], [1e6 * 1e6], {'from': STRATEGIST})
after = vault_core.totalValue()
print("Profit In", c18(after-before))

vault_admin.reallocate(MORPHO_AAVE_STRAT, MORPHO_COMP_STRAT, [USDC], [1e6 * 1e6], {'from': STRATEGIST})
after2 = vault_core.totalValue()
print("Profit Almost Full Cycle", c18(after2-before))

vault_admin.withdrawAllFromStrategy(MORPHO_AAVE_STRAT, {'from': STRATEGIST})
after3 = vault_core.totalValue()
print("Profit Full Cycle", c18(after3-before))
```

**Review by DanielVF — APPROVED** [review]
Deploy process review complete, though we shouldn't merge until the underlying contract PR has been reviewed.

**Comment by shahthepro** [comment]
@DanielVF I had to redeploy the contracts due to a code change. We should also cancel the previous proposal 42, the new proposal ID is 43. Have updated the PR description with the new addresses and proposal ID. Would you mind reviewing them again?

**Comment by sparrowDom** [comment]
Both the original PR and this deploy one look good. I have: 
- merged in this PR locally: https://github.com/OriginProtocol/origin-dollar/pull/1212
- have set local node to a recent block `16335242`
- have ran `yarn run test:fork`

this makes the fork environment identify the proposal and execute it: 
```
Running 047_morpho_aave_strategy deployment...
Found proposal id: 43 on forked network. Executing proposal containing deployment of: 047_morpho_aave_strategy
INFO: Impersonated Guardian at 0xbe2AB3d3d8F6a32b96414ebbd865dBD276d3d899
INFO: Proposal 43 queued
INFO: Advancing time by 48 hours + 1 second for TimeLock delay.
INFO: Proposal 43 executed
047_morpho_aave_strategy deploy done.
```

and run all the fork tests on top of that and they passed: 
Screenshot 2023-01-04 at 20 05 11

**Code verification**
MorphoAaveStrategyProxy deployed at 0x79F2188EF9350A1dC11A062cca0abE90684b0197 has the exact code as in our codebase. And points to implementation address: [0xC72bda59E382be10bb5D71aBd01Ecc65aa16fD83](https://etherscan.io/address/0xC72bda59E382be10bb5D71aBd01Ecc65aa16fD83)

MorphoAaveStrategy implementation contract deployed at 0xC72bda59E382be10bb5D71aBd01Ecc65aa16fD83 has the exact code as in our codebase.

**Governance proposal #43**
|Id|Contract|Function|CallData|
|---|---|------|------|
|------|------|------|------|
|------|------|------|------|

0x79F2188EF9350A1dC11A062cca0abE90684b0197
0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70
0x21Fb5812D70B3396880D30e90D9e5C1202266c89
0x79F2188EF9350A1dC11A062cca0abE90684b0197

**Review by sparrowDom — APPROVED** [review]
All checks out good job @shahthepro

**Comment by DanielVF** [comment]
✅ Second deploy looks good.

- [x] Deployed contract verified code (and dependancies) match the final PR commit's code
- [x] The transactions that interacted with the newly deployed contract match the deploy script.
- [x] Governance proposal matches the deploy script
- [x] Smoke tests pass after fork test execution of the governance proposal
- [x] Update Docs

**Pull request merged**
