### PR TITLE
Change pause deposits to pause capital

### PR DESCRIPTION
**Pull request by tomlinton**
Extends what was previously pauseDeposits to include redeems and allocates. Renamed the flag to pauseCapital. I couldn't think of a better name.

Contract change checklist:
  - [x] Code reviewed by 2 reviewers
  - [ ] Unit tests pass
  - [x] Slither tests pass with no warning
  - [ ] Echidna tests pass (not automated, run manually on local)

### CODE REVIEW

**Review by franckc — APPROVED** [review]
LGTM

**Review by shahthepro — APPROVED** [review]
Looks good to me. 

Wondering if we should also add the `whenNotCapitalPaused` modifier to `VaultAdmin.removeStrategy` and `VaultAdmin.reallocate` methods. But since those methods are only callable by governor, it shouldn't be a problem.

**Comment by franckc** [comment]
@tomlinton Please see @shahthepro 's question above. Since that does not involve the Governor or Timelock, I'm going to go ahead and merge this PR in so that I can go ahead with the deploy. If needed we can address that comment as a separate PR.

**Comment by tomlinton** [comment]
Yea I had the same thoughts as @shahthepro

**Pull request merged**
