### PR TITLE
conditional staking banner

### PR DESCRIPTION
**Pull request by rolandpo**
Conditional staking banner that appears for connected users that either currently have or or have had active stakes. The earn page here gets removed from the dapp navigation. I think this waits for wOUSD interface to be deployed or whatever replaces staking.

Screenshot 2022-04-29 at 12 44 56

### CODE REVIEW

**Review by sparrowDom — COMMENTED** [review]
Found some issues on the marketing pages and mobile layout. Can you check it out please?
Screenshot 2022-05-04 at 13 33 41
Screenshot 2022-05-04 at 13 32 58

**Comment by rolandpo** [comment]
should be fixed now

**Comment by sparrowDom** [comment]
This is ready to be merged. Just need a confirmation we are ok discontinuing earn page

**Review by sparrowDom — APPROVED** [review]
nice work LGTM!

**Comment by rolandpo** [comment]
I've resolved conflicts in the layout file, I think someone still has to update the production and staging env vars

**Comment by rolandpo** [comment]
moved to #1036

**Pull request closed without merging**
